name: cluster_config_create
pack: proxmox
runner_type: python-script
description: "Generate new cluster configuration."
enabled: true
entry_point: "cluster_config_create.py"
parameters:
  clustername:
    description: "The name of the cluster."
    type: string
    required: true
  link_list:
    description: "Address and priority information of a single corosync link."
    type: string
    required: false
  nodeid:
    description: "Node id for this node."
    type: integer
    required: false
  votes:
    description: "Number of votes for this node."
    type: integer
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
