name: nodes_node_qemu_vmid_config_vm_config
pack: proxmox
runner_type: python-script
description: "Get current virtual machine configuration. This does not include pending configuration changes (see 'pending' API)."
enabled: true
entry_point: "nodes_node_qemu_vmid_config_vm_config.py"
parameters:
  current:
    description: "Get current values (instead of pending values)."
    default: False
    type: boolean
    required: false
  node:
    description: "The cluster node name."
    type: string
    required: true
  snapshot:
    description: "Fetch config values from given snapshot."
    type: string
    required: false
  vmid:
    description: "The (unique) ID of the VM."
    type: integer
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
