name: nodes_node_config_get_config
pack: proxmox
runner_type: python-script
description: "Get node configuration options."
enabled: true
entry_point: "nodes_node_config_get_config.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
  prox_property:
    description: "Return only a specific property from the node configuration."
    default: "all"
    enum:
      - acme
      - description
      - startall-onboot-delay
      - wakeonlan
    type: string
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
