name: cluster_acme_plugins_id_get_plugin_config
pack: proxmox
runner_type: python-script
description: "Get ACME plugin configuration."
enabled: true
entry_point: "cluster_acme_plugins_id_get_plugin_config.py"
parameters:
  prox_id:
    description: "Unique identifier for ACME plugin instance."
    type: string
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
