name: cluster_config_join
pack: proxmox
runner_type: python-script
description: "Joins this node into an existing cluster."
enabled: true
entry_point: "cluster_config_join.py"
parameters:
  fingerprint:
    description: "Certificate SHA 256 fingerprint."
    type: string
    required: true
  force:
    description: "Do not throw error if node already exists."
    type: boolean
    required: false
  hostname:
    description: "Hostname (or IP) of an existing cluster member."
    type: string
    required: true
  link_list:
    description: "Address and priority information of a single corosync link."
    type: string
    required: false
  nodeid:
    description: "Node id for this node."
    type: integer
    required: false
  password:
    description: "Superuser (root) password of peer node."
    secret: true
    type: string
    required: true
  votes:
    description: "Number of votes for this node"
    type: integer
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
