name: nodes_node_ceph_config
pack: proxmox
runner_type: python-script
description: "Get Ceph configuration."
enabled: true
entry_point: "nodes_node_ceph_config.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
