name: nodes_node_network_reload_network_config
pack: proxmox
runner_type: python-script
description: "Reload network configuration"
enabled: true
entry_point: "nodes_node_network_reload_network_config.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
