name: cluster_config_nodes_node_delnode
pack: proxmox
runner_type: python-script
description: "Removes a node from the cluster configuration."
enabled: true
entry_point: "cluster_config_nodes_node_delnode.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
