name: cluster_config_totem
pack: proxmox
runner_type: python-script
description: "Get corosync totem protocol settings."
enabled: true
entry_point: "cluster_config_totem.py"
parameters:
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
