name: cluster_config_nodes_node_addnode
pack: proxmox
runner_type: python-script
description: "Adds a node to the cluster configuration. This call is for internal use."
enabled: true
entry_point: "cluster_config_nodes_node_addnode.py"
parameters:
  force:
    description: "Do not throw error if node already exists."
    type: boolean
    required: false
  link_list:
    description: "Address and priority information of a single corosync link."
    type: string
    required: false
  node:
    description: "The cluster node name."
    type: string
    required: true
  nodeid:
    description: "Node id for this node."
    type: integer
    required: false
  votes:
    description: "Number of votes for this node"
    type: integer
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
