name: cluster_config_qdevice_status
pack: proxmox
runner_type: python-script
description: "Get QDevice status"
enabled: true
entry_point: "cluster_config_qdevice_status.py"
parameters:
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
