name: cluster_config_create
pack: proxmox
runner_type: python-script
description: "Generate new cluster configuration. If no links given, default to local IP address as link0."
enabled: true
entry_point: "cluster_config_create.py"
parameters:
  api_timeout:
    description: "Time in seconds to wait for API response. (Default: 5)"
    type: integer
    required: false
    default: 5
  clustername:
    description: "The name of the cluster."
    type: string
    required: true
  link_list:
    description: "Address and priority information of a single corosync link. (up to 8 links supported; link0..link7)"
    type: string
    required: false
  nodeid:
    description: "Node id for this node."
    type: integer
    required: false
  votes:
    description: "Number of votes for this node."
    type: integer
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
