name: cluster_config_join_join_info
pack: proxmox
runner_type: python-script
description: "Get information needed to join this cluster over the connected node."
enabled: true
entry_point: "cluster_config_join_join_info.py"
parameters:
  node:
    description: "The node for which the joinee gets the nodeinfo. "
    type: string
    required: false
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
