name: cluster_config_nodes_node_delnode
pack: proxmox
runner_type: python-script
description: "Removes a node from the cluster configuration."
enabled: true
entry_point: "cluster_config_nodes_node_delnode.py"
parameters:
  api_timeout:
    description: "Time in seconds to wait for API response. (Default: 5)"
    type: integer
    required: false
    default: 5
  node:
    description: "The cluster node name."
    type: string
    required: true
  profile_name:
    description: "The profile to use to run the action."
    type: string
    required: false
