name: nodes_qemu_snapshot_config_update_snapshot_config
pack: proxmox
runner_type: python-script
description: "Update snapshot metadata."
enabled: true
entry_point: "nodes_qemu_snapshot_config_update_snapshot_config.py"
parameters:
  description:
    description: "A textual description or comment."
    type: string
    required: false
  node:
    description: "The cluster node name."
    type: string
    required: true
  snapname:
    description: "The name of the snapshot."
    type: string
    required: true
  vmid:
    description: "The (unique) ID of the VM."
    type: integer
    required: true
