name: nodes_ceph_config
pack: proxmox
runner_type: python-script
description: "Get Ceph configuration."
enabled: true
entry_point: "nodes_ceph_config.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
    secret: false
