name: nodes_lxc_config_update_vm
pack: proxmox
runner_type: python-script
description: "Set container options."
enabled: true
entry_point: "nodes_lxc_config_update_vm.py"
parameters:
  arch:
    description: "OS architecture type."
    default: "amd64"
    enum:
      - amd64
      - i386
      - arm64
      - armhf
    type: string
    required: false
    secret: false
  cmode:
    description: "Console mode. By default, the console command tries to open a connection to one of the available tty devices. By setting cmode to 'console' it tries to attach to /dev/console instead. If you set cmode to 'shell', it simply invokes a shell inside the container (no login)."
    default: "tty"
    enum:
      - shell
      - console
      - tty
    type: string
    required: false
    secret: false
  console:
    description: "Attach a console device (/dev/console) to the container."
    default: 1
    type: boolean
    required: false
    secret: false
  cores:
    description: "The number of cores assigned to the container. A container can use all available cores by default."
    type: integer
    required: false
    secret: false
  cpulimit:
    description: "Limit of CPU usage.\n\nNOTE: If the computer has 2 CPUs, it has a total of '2' CPU time. Value '0' indicates no CPU limit."
    default: 0
    type: number
    required: false
    secret: false
  cpuunits:
    description: "CPU weight for a VM. Argument is used in the kernel fair scheduler. The larger the number is, the more CPU time this VM gets. Number is relative to the weights of all the other running VMs.\n\nNOTE: You can disable fair-scheduler configuration by setting this to 0."
    default: 1024
    type: integer
    required: false
    secret: false
  debug:
    description: "Try to be more verbose. For now this only enables debug log-level on start."
    default: 0
    type: boolean
    required: false
    secret: false
  delete:
    description: "A list of settings you want to delete."
    type: string
    required: false
    secret: false
  description:
    description: "Description for the Container. Shown in the web-interface CT's summary. This is saved as comment inside the configuration file."
    type: string
    required: false
    secret: false
  digest:
    description: "Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications."
    type: string
    required: false
    secret: false
  features:
    description: "Allow containers access to advanced features."
    type: string
    required: false
    secret: false
  hookscript:
    description: "Script that will be exectued during various steps in the containers lifetime."
    type: string
    required: false
    secret: false
  hostname:
    description: "Set a host name for the container."
    type: string
    required: false
    secret: false
  lock:
    description: "Lock/unlock the VM."
    enum:
      - backup
      - create
      - destroyed
      - disk
      - fstrim
      - migrate
      - mounted
      - rollback
      - snapshot
      - snapshot-delete
    type: string
    required: false
    secret: false
  memory:
    description: "Amount of RAM for the VM in MB."
    default: 512
    type: integer
    required: false
    secret: false
  mp:
    description: "Use volume as container mount point. Use the special syntax STORAGE_ID:SIZE_IN_GiB to allocate a new volume."
    type: string
    required: false
    secret: false
  nameserver:
    description: "Sets DNS server IP address for a container. Create will automatically use the setting from the host if you neither set searchdomain nor nameserver."
    type: string
    required: false
    secret: false
  net:
    description: "Specifies network interfaces for the container."
    type: string
    required: false
    secret: false
  node:
    description: "The cluster node name."
    type: string
    required: true
    secret: false
  onboot:
    description: "Specifies whether a VM will be started during system bootup."
    default: 0
    type: boolean
    required: false
    secret: false
  ostype:
    description: "OS type. This is used to setup configuration inside the container, and corresponds to lxc setup scripts in /usr/share/lxc/config/<ostype>.common.conf. Value 'unmanaged' can be used to skip and OS specific setup."
    enum:
      - debian
      - devuan
      - ubuntu
      - centos
      - fedora
      - opensuse
      - archlinux
      - alpine
      - gentoo
      - unmanaged
    type: string
    required: false
    secret: false
  protection:
    description: "Sets the protection flag of the container. This will prevent the CT or CT's disk remove/update operation."
    default: 0
    type: boolean
    required: false
    secret: false
  revert:
    description: "Revert a pending change."
    type: string
    required: false
    secret: false
  rootfs:
    description: "Use volume as container root."
    type: string
    required: false
    secret: false
  searchdomain:
    description: "Sets DNS search domains for a container. Create will automatically use the setting from the host if you neither set searchdomain nor nameserver."
    type: string
    required: false
    secret: false
  startup:
    description: "Startup and shutdown behavior. Order is a non-negative number defining the general startup order. Shutdown in done with reverse ordering. Additionally you can set the 'up' or 'down' delay in seconds, which specifies a delay to wait before the next VM is started or stopped."
    type: string
    required: false
    secret: false
  swap:
    description: "Amount of SWAP for the VM in MB."
    default: 512
    type: integer
    required: false
    secret: false
  tags:
    description: "Tags of the Container. This is only meta information."
    type: string
    required: false
    secret: false
  template:
    description: "Enable/disable Template."
    default: 0
    type: boolean
    required: false
    secret: false
  timezone:
    description: "Time zone to use in the container. If option isn't set, then nothing will be done. Can be set to 'host' to match the host time zone, or an arbitrary time zone option from /usr/share/zoneinfo/zone.tab"
    type: string
    required: false
    secret: false
  tty:
    description: "Specify the number of tty available to the container"
    default: 2
    type: integer
    required: false
    secret: false
  unprivileged:
    description: "Makes the container run as unprivileged user. (Should not be modified manually.)"
    default: 0
    type: boolean
    required: false
    secret: false
  unused:
    description: "Reference to unused volumes. This is used internally, and should not be modified manually."
    type: string
    required: false
    secret: false
  vmid:
    description: "The (unique) ID of the VM."
    type: integer
    required: true
    secret: false
