name: nodes_network_network_config
pack: proxmox
runner_type: python-script
description: "Read network device configuration"
enabled: true
entry_point: "nodes_network_network_config.py"
parameters:
  iface:
    description: "Network interface name."
    type: string
    required: true
    secret: false
  node:
    description: "The cluster node name."
    type: string
    required: true
    secret: false
