name: nodes_vzdump_extractconfig
pack: proxmox
runner_type: python-script
description: "Extract configuration from vzdump backup archive."
enabled: true
entry_point: "nodes_vzdump_extractconfig.py"
parameters:
  node:
    description: "The cluster node name."
    type: string
    required: true
  volume:
    description: "Volume identifier"
    type: string
    required: true
