name: nodes_lxc_config_vm_config
pack: proxmox
runner_type: python-script
description: "Get container configuration."
enabled: true
entry_point: "nodes_lxc_config_vm_config.py"
parameters:
  current:
    description: "Get current values (instead of pending values)."
    default: 0
    type: boolean
    required: false
  node:
    description: "The cluster node name."
    type: string
    required: true
  snapshot:
    description: "Fetch config values from given snapshot."
    type: string
    required: false
  vmid:
    description: "The (unique) ID of the VM."
    type: integer
    required: true
