name: nodes_qemu_config_vm_config
pack: proxmox
runner_type: python-script
description: "Get the virtual machine configuration with pending configuration changes applied. Set the 'current' parameter to get the current configuration instead."
enabled: true
entry_point: "nodes_qemu_config_vm_config.py"
parameters:
  current:
    description: "Get current values (instead of pending values)."
    default: 0
    type: boolean
    required: false
    secret: false
  node:
    description: "The cluster node name."
    type: string
    required: true
    secret: false
  snapshot:
    description: "Fetch config values from given snapshot."
    type: string
    required: false
    secret: false
  vmid:
    description: "The (unique) ID of the VM."
    type: integer
    required: true
    secret: false
